# Generated by Django 4.2.7 on 2023-12-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houserent',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
