# Generated by Django 4.2.7 on 2023-12-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0003_houserent_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='houserent',
            name='building_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='houserent',
            name='land_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
