# Generated by Django 4.2.7 on 2023-12-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0005_houserent_bath'),
    ]

    operations = [
        migrations.AddField(
            model_name='houserent',
            name='status',
            field=models.CharField(default='rent', max_length=10),
        ),
    ]
