# Generated by Django 4.2.7 on 2023-12-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0006_houserent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houserent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
