# Generated by Django 4.2.7 on 2023-12-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0007_alter_houserent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(choices=[('Apartment', 'Apartment'), ('Single_Room', 'Single Room')], max_length=50)),
                ('status', models.CharField(default='sale', max_length=10)),
                ('price', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('sub_location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('gps_address', models.CharField(max_length=20)),
                ('image_1', models.ImageField(upload_to='houseRent')),
                ('image_2', models.ImageField(upload_to='houseRent')),
                ('image_3', models.ImageField(upload_to='houseRent')),
                ('image_4', models.ImageField(upload_to='houseRent')),
                ('image_5', models.ImageField(upload_to='houseRent')),
                ('video', models.ImageField(upload_to='houseRent')),
                ('pool', models.BooleanField()),
                ('car_park', models.BooleanField()),
                ('rooms', models.CharField(max_length=50)),
                ('bed', models.CharField(blank=True, max_length=10, null=True)),
                ('building_size', models.CharField(blank=True, max_length=10, null=True)),
                ('land_size', models.CharField(blank=True, max_length=10, null=True)),
                ('bath', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
