# Generated by Django 3.2.16 on 2024-01-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0010_alter_landsale_image_2_alter_landsale_image_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='houserent',
            name='property_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='housesale',
            name='property_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landsale',
            name='property_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
