# Generated by Django 4.2.7 on 2024-01-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0011_auto_20240102_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproperties',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='price',
            field=models.IntegerField(),
        ),
    ]
