# Generated by Django 4.2.7 on 2024-01-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0013_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
