# Generated by Django 4.2.7 on 2024-01-07 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0014_alter_feedback_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(blank=True, max_length=20, null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='houserent',
            name='status',
            field=models.CharField(default='house_rent', max_length=10),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='status',
            field=models.CharField(default='house_sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='status',
            field=models.CharField(default='land_sale', max_length=10),
        ),
    ]
