# Generated by Django 4.2.7 on 2024-01-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0015_wishlist_alter_houserent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
