# Generated by Django 4.2.7 on 2024-01-23 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0017_houselease_remove_houserent_bath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselease',
            name='admin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='houselease',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='houserent',
            name='admin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='houserent',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='housesale',
            name='admin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='housesale',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
