# Generated by Django 4.2.7 on 2024-01-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0018_houselease_admin_houselease_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselease',
            name='property_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='houserent',
            name='property_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='housesale',
            name='property_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
