# Generated by Django 4.2.7 on 2024-01-23 20:28

from django.db import migrations, models
import sikadahomesApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0019_houselease_property_id_houserent_property_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houserent',
            name='img_front',
            field=models.ImageField(blank=True, null=True, upload_to=sikadahomesApp.models.HouseRent.image_upload_path),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='img_gallery_1',
            field=models.ImageField(blank=True, null=True, upload_to=sikadahomesApp.models.HouseRent.image_upload_path),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='img_gallery_2',
            field=models.ImageField(blank=True, null=True, upload_to=sikadahomesApp.models.HouseRent.image_upload_path),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='img_gallery_3',
            field=models.ImageField(blank=True, null=True, upload_to=sikadahomesApp.models.HouseRent.image_upload_path),
        ),
        migrations.AlterField(
            model_name='houserent',
            name='img_listing',
            field=models.ImageField(blank=True, null=True, upload_to=sikadahomesApp.models.HouseRent.image_upload_path),
        ),
    ]
