# Generated by Django 4.2.7 on 2024-01-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0020_alter_houserent_img_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houserent',
            name='img_listing',
            field=models.ImageField(blank=True, null=True, upload_to='HouseRent/<function HouseRent.image_upload_path at 0x000002B8E3E5C430>/'),
        ),
    ]
