# Generated by Django 4.2.7 on 2024-01-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0024_houselease_location_houserent_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landsale',
            old_name='title',
            new_name='property_title',
        ),
        migrations.RenameField(
            model_name='landsale',
            old_name='sub_location',
            new_name='region',
        ),
        migrations.AlterField(
            model_name='landsale',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='status',
            field=models.CharField(blank=True, default='land_for_sale', max_length=100, null=True),
        ),
    ]
