# Generated by Django 4.2.7 on 2024-01-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0025_rename_title_landsale_property_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landsale',
            old_name='image_2',
            new_name='img_front',
        ),
        migrations.RenameField(
            model_name='landsale',
            old_name='image_1',
            new_name='img_listing',
        ),
        migrations.RemoveField(
            model_name='landsale',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='landsale',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='landsale',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='landsale',
            name='video',
        ),
    ]
