# Generated by Django 4.2.7 on 2024-01-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0026_rename_image_2_landsale_img_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landsale',
            name='img_listing',
            field=models.ImageField(blank=True, null=True, upload_to='houseRent'),
        ),
    ]
