# Generated by Django 3.2.16 on 2024-01-27 21:45

from django.db import migrations, models
import django.utils.timezone
import sikadahomesApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0027_alter_landsale_img_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='landsale',
            name='admin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landsale',
            name='budget',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='landsale',
            name='commercial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landsale',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landsale',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='landsale',
            name='no_of_plots',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landsale',
            name='plot_dimensions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landsale',
            name='property_address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='landsale',
            name='property_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='img_front',
            field=models.ImageField(blank=True, null=True, upload_to=sikadahomesApp.models.LandSale.image_upload_path),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='img_listing',
            field=models.ImageField(blank=True, null=True, upload_to=sikadahomesApp.models.LandSale.image_upload_path),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
