# Generated by Django 3.2.16 on 2024-01-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0028_auto_20240127_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='landsale',
            name='electricity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landsale',
            name='water',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='gps_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='landsale',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
