# Generated by Django 3.2.16 on 2024-01-28 18:53

from django.db import migrations, models
import sikadahomesApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0029_auto_20240128_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='landsale',
            name='video_land',
            field=models.ImageField(blank=True, null=True, upload_to=sikadahomesApp.models.LandSale.image_upload_path),
        ),
        migrations.AddField(
            model_name='landsale',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=sikadahomesApp.models.LandSale.image_upload_path),
        ),
    ]
