# Generated by Django 5.0.1 on 2024-03-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0034_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='Feedback/Profile'),
        ),
    ]
