# Generated by Django 5.0.1 on 2024-03-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0035_feedback_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='service_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
