# Generated by Django 5.0.1 on 2024-04-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0037_message_save_my_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='propety_ids',
            new_name='propety_id',
        ),
    ]
