# Generated by Django 5.0.1 on 2024-05-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0040_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='img_listing',
            field=models.ImageField(blank=True, null=True, upload_to='CartImage'),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
