# Generated by Django 5.0.1 on 2024-05-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0041_cart_img_listing_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
