# Generated by Django 5.0.1 on 2024-05-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0042_cart_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='img_listing',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='title',
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
