# Generated by Django 5.0.1 on 2024-05-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0043_remove_cart_img_listing_remove_cart_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
