# Generated by Django 5.0.1 on 2024-05-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0044_orders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproperties',
            name='property_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=200, null=True),
        ),
    ]
