# Generated by Django 5.0.1 on 2024-05-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0045_allproperties_property_title_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
