# Generated by Django 5.0.1 on 2024-06-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0047_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housesale',
            name='img_front',
        ),
        migrations.RemoveField(
            model_name='housesale',
            name='img_gallery_1',
        ),
        migrations.RemoveField(
            model_name='housesale',
            name='img_gallery_2',
        ),
        migrations.RemoveField(
            model_name='housesale',
            name='img_gallery_3',
        ),
        migrations.AlterField(
            model_name='housesale',
            name='img_listing',
            field=models.ImageField(blank=True, null=True, upload_to='Hello_Images/'),
        ),
    ]
