# Generated by Django 5.0.1 on 2024-06-06 19:52

import sikadahomesApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0048_remove_housesale_img_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housesale',
            name='img_front',
            field=models.ImageField(blank=True, null=True, upload_to=sikadahomesApp.models.HouseSale.image_upload_path),
        ),
        migrations.AddField(
            model_name='housesale',
            name='img_gallery_1',
            field=models.ImageField(blank=True, null=True, upload_to=sikadahomesApp.models.HouseSale.image_upload_path),
        ),
        migrations.AddField(
            model_name='housesale',
            name='img_gallery_2',
            field=models.ImageField(blank=True, null=True, upload_to=sikadahomesApp.models.HouseSale.image_upload_path),
        ),
        migrations.AddField(
            model_name='housesale',
            name='img_gallery_3',
            field=models.ImageField(blank=True, null=True, upload_to=sikadahomesApp.models.HouseSale.image_upload_path),
        ),
        migrations.AlterField(
            model_name='housesale',
            name='img_listing',
            field=models.ImageField(blank=True, null=True, upload_to=sikadahomesApp.models.HouseSale.image_upload_path),
        ),
    ]
