# Generated by Django 5.0.1 on 2024-07-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikadahomesApp', '0049_housesale_img_front_housesale_img_gallery_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselease',
            name='condition',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('sold', 'Sold'), ('deleted', 'Deleted'), ('active', 'Active')], max_length=30, null=True),
        ),
    ]
